export const FETCH_ALL_TRENDING_NEWS_ACTION = 'FETCH_TRENDING_NEWS';
export const TOKEN_INFO = 'TOKEN_INFO';
export const PRICE_GRAPH = 'PRICE_GRAPH';
export const NUM_OF_DAYS = 'NUM_OF_DAYS';
export const WALLET_ADDRESS = 'WALLET_ADDRESS';
export const SELECT_NETWORK = 'SELECT_NETWORK';
export const TOKEN_STATS_DATA = 'TOKEN_STATS_DATA';
export const TOKENS_MINTED = 'TOKEN_MINTED';
